### ISSUE TITLE
Not_found

### ISSUE THREAD

**Issue by laibulle** [rrdelaney/ReasonablyTyped#61]
Hello,

I am trying to convert react-navigation from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-navigation but I get this output

```
[ 'Not_found', -6, tag: 248 ]
Error: N
    at Object.compile (/Users/laibulle/ReasonablyTyped/lib/index.js:56:11)
    at fs.readFile (/Users/laibulle/ReasonablyTyped/lib/cli.js:61:40)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
```

* **ReasonablyTyped version:** 0.13.0 but actually it is from master
* **bs-platform version:** BuckleScript 3.0.0 (Using OCaml4.02.3+BS )

**Comment by rrdelaney** [comment]
`master` is currently very broken for TS definitions, sorry 😞 I'm working on rewriting all of the TS integration atm
