### ISSUE TITLE
All 2.0.0 npm installs crash

### ISSUE THREAD

**Issue by nickpascucci** [rrdelaney/ReasonablyTyped#62]
The `retyped` command crashes when installing the 2.0.0 releases from npm.

* **ReasonablyTyped version:** 2.0.0-beta4
* **bs-platform version:** BuckleScript 3.1.5 (Using OCaml4.02.3+BS )

```
{SANDBOX} [17:39:43] /src/types/hellojs [master] > retyped index.d.ts
module.js:549
    throw err;
    ^

Error: Cannot find module './js/src/compiler'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nick/.npm-global/lib/node_modules/reasonably-typed/lib/index.js:2:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by bbqbaron** [comment]
This is just a matter of not having shipped the JS artifacts, right? For instance, I can fix this by running `bsb -make-world` in the install directory (not that that's the solution :P). I'm new at NPM, but is this just fixed by having a [prepublishOnly](https://docs.npmjs.com/misc/scripts) hook that produces the JS artifacts? On the other hand (I was curious and browsed around) it looks like [reason-react](https://github.com/reasonml/reason-react/tree/master/lib/js/src) commits their artifacts to source. Does a more experienced NPM person know what to do?

**Comment by rrdelaney** [comment]
2.0 isn't ready yet, sorry! It still needs a ton of work to handle most cases. The main driving factor for 2.0 is to be the backing library for [styled-scss](https://github.com/rrdelaney/styled-scss), and it's super not ready for CLI usage

**Comment by dmtrKovalenko** [comment]
@rrdelaney please provide separate npm tag if you are publishing `beta` version like `npm publish --tag next` 
But anyway if you are publishing it to npm it must be ready for usage.
